aks-baseline-regulated -- Adding Secrets Store native CSI Driver for Kubernetes
mspnp/aks-baseline-regulated pull request #21
Opened 2021-06-22 18:31 UTC by magrande

2021-06-22 21:13 UTC, ckittel requested changes
w00t!

In addition to the comments below, there is also a paragraph in the `10-pre-bootstrap` file that needs to be changed significantly because of this migration to the add-on (see line 57).

2021-06-22 21:13 UTC, ckittel commented on cluster-manifests/README.md
> +* Azure KeyVault [Secrets Store CSI Driver for Kubernetes](https://docs.microsoft.com/azure/aks/csi-secrets-store-driver)
This should be removed right, we don't have any more files related to this in here.

2021-06-22 21:13 UTC, ckittel commented on cluster-manifests/cluster-baseline-settings/resource-quota.yaml
>      # csi-secrets-store, csi-secrets-store-provider-azure
Need to remove these lines

2021-06-22 21:13 UTC, ckittel commented on docs/deploy/01-prerequisites.md
Just to match the formatting of the above items.

```suggestion
```

2021-06-22 21:13 UTC, ckittel commented on docs/deploy/11-gitops.md
>     kubectl apply -k cluster-baseline-settings
I don't think we need to do this anymore.  I think we only had to do this because we needed CSI in place before we'd start syncing, or the ingress controller would fail to deploy. I can't think of any reason we'd need av/fim/kured/limit-ranges/network policy/rbac/resource-quotas in place in this namespace before moving forward.  Can you test without doing this step now and make sure it works?

2021-06-22 21:30 UTC, magrande commented on docs/deploy/11-gitops.md
>     kubectl apply -k cluster-baseline-settings
You mean just not doing this step, but keeping the folder the ways it is now in this PR, right ?  Ok ! I will test it

2021-06-22 21:32 UTC, magrande commented on cluster-manifests/README.md
> +* Azure KeyVault [Secrets Store CSI Driver for Kubernetes](https://docs.microsoft.com/azure/aks/csi-secrets-store-driver)
Done

2021-06-22 21:32 UTC, magrande commented on cluster-manifests/cluster-baseline-settings/resource-quota.yaml
>      # csi-secrets-store, csi-secrets-store-provider-azure
Removed

2021-06-22 21:33 UTC, magrande commented
> w00t!
> 
> In addition to the comments below, there is also a paragraph in the `10-pre-bootstrap` file that needs to be changed significantly because of this migration to the add-on (see line 57).

Right !  good catch, I modified it a bit, please take a look and let me know how it looks like

2021-06-22 21:35 UTC, ckittel commented on docs/deploy/11-gitops.md
>     kubectl apply -k cluster-baseline-settings
That's correct.  My brain is telling me that the ONLY reason we had to run that line was to get the CSI driver up and running before flux came in with secrets for the ingress controller.  But need to validate.

2021-06-22 21:41 UTC, ckittel requested changes

2021-06-22 21:41 UTC, ckittel commented on docs/deploy/10-pre-bootstrap.md
> +   > For simplicity we are NOT importing images that are coming from Microsoft Container Registry's (MCR) `oss` repository. This is not an endorsement of the suitability of those images to be pulled
The wording for this paragraph is not accurate after your change. I'm pretty sure this whole paragraph can be removed or maybe better, changed in its core messaging. I'm pretty sure this is the LAST mcr reference, so you'll want to remove the mentioned Azure Policy exception like the paragraph says to do.  I'll let you take another swing at editing this up, let me know if you need help.

2021-06-24 18:35 UTC, ckittel commented on docs/deploy/10-pre-bootstrap.md
> +   > For simplicity we are NOT importing images that are coming from Microsoft Container Registry's (MCR) `oss` repository. This is not an endorsement of the suitability of those images to be pulled
```suggestion
   > The above imports account for 100% of the containers that you are actively bringing to the cluster, but not those that come with the AKS service itself or any of its add-ons. Those images, outside of your direct control, are all sourced from Microsoft Container Registry's (MCR). While you do not have an affordance to inject yourself in the middle of their distribution to your cluster, you can still pull those images through your inspection process for your own audit and reporting purposes. _All container images that you directly bring to the cluster should pass through your quarantine process._ The _Allowed Images_ Azure Policy associated with this cluster should be configured to match your specific needs. Be sure to update `allowedContainerImagesRegex` in [`cluster-stamp.json`](../../cluster-stamp.json) to define expected image sources to whatever specificity is manageable for you. Never allow a source that you do not intend to use. For example, if you do not bring Open Service Mesh into your cluster, you can remove the existing allowance for `mcr.microsoft.com` as a valid source of images, leaving just `<your acr instance>/live/` repositories as the only valid source for non-system namespaces.
```

2021-06-24 20:20 UTC, ckittel commented on cluster-stamp.json
> +                        "value": "[concat(variables('defaultAcrName'), '\.azurecr\.io\/live\/.+$|mcr\.microsoft\.com\/oss\/(openservicemesh\/init:|envoyproxy\/envoy:).+$')]"
Did you test that these apply the way we want them to?

2021-06-24 20:25 UTC, ckittel commented on cluster-stamp.json
> +                        "value": "[concat(variables('defaultAcrName'), '\.azurecr\.io\/live\/.+$|mcr\.microsoft\.com\/oss\/(openservicemesh\/init:|envoyproxy\/envoy:).+$')]"
Specifically want to make sure we don't need to DOUBLE escape the escape character when it's applied here from the arm template.

2021-06-25 15:38 UTC, ckittel commented on cluster-stamp.json
> +                        "value": "[concat(variables('defaultAcrName'), '\.azurecr\.io\/live\/.+$|mcr\.microsoft\.com\/oss\/(openservicemesh\/init:|envoyproxy\/envoy:).+$')]"
Thanks for testing

2021-06-25 15:38 UTC, ckittel approved these changes
Thank you for the work on this!  💪

2021-06-25 15:39 UTC, merged