AKS baseline regulated - moving firewall rules out from Azure Firewall separate rule set
mspnp/aks-baseline-regulated pull request #23
Opened 2021-07-08 17:41 UTC by magrande

2021-07-09 14:17 UTC, ckittel requested changes
LMK if you have any questions.  Nice work on the change over

2021-07-09 14:17 UTC, ckittel commented on networking/hub-region.v2.json
> +                                        "destinationAddresses": [],
Order doesn't match v1, making this look like a diff. when it shouldn't be.  Also `webCategories` and `destinationAddresses` are not in v1

2021-07-09 14:17 UTC, ckittel commented on networking/hub-region.v2.json
> -                                    "description": "This is required as the Packer VM needs to install Azure CLI. [Step performed in the referenced jump box building process. Not needed if your jump
In this migration, we are loosing these comments which I've been told are valuable.  Now `description` actually is valid in the REST API, but doesn't look like it's in the ARM schemas yet.  Can you bring them over as comments at least so we don't lose them.

2021-07-12 15:29 UTC, magrande commented on networking/hub-region.v2.json
> -                                    "description": "This is required as the Packer VM needs to install Azure CLI. [Step performed in the referenced jump box building process. Not needed if your jump
Done !

2021-07-12 15:29 UTC, magrande commented on networking/hub-region.v2.json
> +                                        "destinationAddresses": [],
Fixed

2021-07-12 15:30 UTC, magrande commented on networking/hub-region.v2.json
> +                                        "destinationAddresses": [],
Fixed

2021-07-12 15:30 UTC, magrande commented on networking/hub-region.v1.json
> +                                            "name": "to-azuremanagement",
Fixed in rules and in ruleCollections as well

2021-07-12 15:31 UTC, magrande commented on networking/hub-region.v1.json
> +                                            "ruleType": "ApplicationRule",
Fixed

2021-07-12 15:32 UTC, magrande commented on networking/hub-region.v1.json
> +        "fwPoliciesBaseName": "fw-policies-base",
I don't get this comment. Those two variables are always placed between hubFwName and hubVNetName in both files. What am I missing ?

2021-07-12 15:34 UTC, magrande commented on networking/hub-region.v1.json
> +        "fwPoliciesBaseName": "fw-policies-base",
I don't get this comment. Those two variables are placed between "hubFwName" and "hubVNetName" in all three files. What am I missing ?

2021-07-13 12:34 UTC, ckittel commented on networking/hub-region.v1.json
> +        "fwPoliciesBaseName": "fw-policies-base",
Sure, but not in the same order, leading to a unremarkable diff when you compare the files.  The only diffs that should be seen when you compare the files are the changes required to fit the narrative.

2021-07-13 12:44 UTC, ckittel commented on networking/hub-region.v1.json
> +          ]
```suggestion
            ]
```
Indent is off, making an unremarkable difference between the files, which we want to strongly avoid.

2021-07-13 12:54 UTC, ckittel commented on networking/hub-region.v2.json
> -                                    "description": "This is required as the Packer VM needs to install Azure CLI. [Step performed in the referenced jump box building process. Not needed if your jump
Thanks! Still missing the migration of the `description` to `//` on network rule `allow-ntp`

2021-07-13 14:04 UTC, ckittel commented on networking/hub-region.v1.json
> +          ]
As mentioned above, this change needs to be in v2 as well.

2021-07-13 14:05 UTC, ckittel commented on networking/hub-region.v2.json
> +                                        "destinationAddresses": [],
`install-terraform` is still off from v1 to v2

2021-07-14 19:06 UTC, ckittel requested changes
All prior feedback items are closed.  Only remaining issues are:

* ipGroup cross-dependency test
* moving ipGroup dependency to the ruleCollection they are consumed by
* Not sure if we can figure out anything about that LA workspace thing... guessing not.
* You'll have to merge `main` in to avoid the merge conflicts

(This list is mostly for myself to remind myself where we left off)

2022-10-21 19:46 UTC, ckittel commented
So far out of date, just closing.

2022-10-21 19:46 UTC, closed without merging