AKS Baseline regulated - AKS 1.23.3 version bump - Also fixing jettech/kube-webhook-certgen bug in the doc
mspnp/aks-baseline-regulated pull request #60
Opened 2022-03-30 19:52 UTC by magrande

2022-03-30 19:54 UTC, magrande commented on docs/deploy/10-pre-bootstrap.md
> +   az acr import --source k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1 -t quarantine/jettech/kube-webhook-certgen:v1.1.1 -n $ACR_NAME_QUARANTINE
This is a bug I introduced. The image path is wrong currently

2022-03-31 13:33 UTC, ckittel requested changes

2022-03-31 13:33 UTC, ckittel commented on cluster-manifests/ingress-nginx/deployment.yaml
> +  whitelist-source-range: 10.240.4.0/24
This will be 5.0/24

2022-03-31 13:33 UTC, ckittel commented on cluster-stamp.v2.json
> +                                    "ipAddress": "10.240.3.244"
This will also be unchanged

2022-03-31 13:33 UTC, ckittel commented on networking/spoke-BU0001A0005-01.json
> +                            "addressPrefix": "10.240.4.0/24",
Move to 5.0/24

2022-03-31 13:53 UTC, magrande commented on cluster-manifests/ingress-nginx/deployment.yaml
> +  loadBalancerIP: 10.240.3.244
Done

2022-03-31 13:53 UTC, magrande commented on cluster-manifests/ingress-nginx/deployment.yaml
> +  whitelist-source-range: 10.240.4.0/24
Done

2022-03-31 13:54 UTC, magrande commented on cluster-stamp.v2.json
> +                                    "ipAddress": "10.240.3.244"
Done

2022-03-31 13:54 UTC, magrande commented on networking/spoke-BU0001A0005-01.json
> +                            "addressPrefix": "10.240.3.240/28",
Reverted

2022-03-31 15:07 UTC, ckittel approved these changes
LGTM!

2022-03-31 15:10 UTC, merged