Bicep subscription
mspnp/aks-baseline-regulated pull request #62
Opened 2022-04-12 23:02 UTC by magrande

2022-04-14 16:55 UTC, ckittel commented on modules/resourceGroupPolicyAssignment.bicep
> +/*** RESOURCES ***/
In our call we talked about making sure to use `existing` resources for these, that way you can do `customPolicyDefinition.displayName` or `builtInPolicyDefinition.displayName` and also `guid(customPolicyDefinition.id, resourceGroup().name)` or `guid(builtInPolicyDefinition.id, resourceGroup().name)` in the `policyAssignment` below.  Any reason that wasn't possible?  Doing it this way ensures the resources exist (as they should, from a dependency perspective)

2022-04-15 19:54 UTC, magrande commented on modules/resourceGroupPolicyAssignment.bicep
> +/*** RESOURCES ***/
Now using existing resource. Looks like it works for both custom and built in policies.

2022-04-19 15:34 UTC, ckittel requested changes
Thanks Mariano! Feedback here in the PR review.  You'll see a couple of patterns.  This is looking on track, nice.

2022-04-19 15:34 UTC, ckittel commented on modules/resourceGroupPolicyAssignment.bicep
> +@description('The desciption of the policy assignment')
```suggestion
@description('The description of the policy assignment.')
```

2022-04-19 15:34 UTC, ckittel commented on modules/resourceGroupPolicyAssignment.bicep
> +@description('Determines whether the policy being assigned is built in or not.')
```suggestion
@description('Indicates whether the policy being assigned is built in or not.')
```

2022-04-19 15:34 UTC, ckittel commented on modules/resourceGroupPolicyAssignment.bicep
> +    name: builtIn ? guid('/providers/Microsoft.Authorization/policyDefinitions/${policyDefintion.name}', resourceGroup().name) : guid(policyDefintion.name, resourceGroup().name)
> policyDefintion.name

? Wouldn't that be `.id` instead?  Did you mean to have this behavior change?

2022-04-19 15:34 UTC, ckittel commented on modules/resourceGroupPolicyAssignment.bicep
> +resource policyDefintion 'Microsoft.Authorization/policyDefinitions@2021-06-01' existing = {
```suggestion
resource policyDefinition 'Microsoft.Authorization/policyDefinitions@2021-06-01' existing = {
```

2022-04-19 15:34 UTC, ckittel commented on modules/resourceGroupPolicyAssignment.bicep
> +        policyDefinitionId: builtIn ? '/providers/Microsoft.Authorization/policyDefinitions/${policyDefintion.name}' : subscriptionResourceId('Microsoft.Authorization/policyDefinitions', policyDefint
Why are you not using the `existing` resource that you fetched above?

2022-04-19 15:34 UTC, ckittel commented on modules/networkWatchersPoliciesDeployment.bicep
> +        policyAssignmentEnforcementMode: 'DoNotEnforce'
The old version had this comment that appears to be lost:

// Since this RG may be under existing policy control in your subscription, adding this policy as audit-only.

That's documentation so we don't get asked "why" -- can you make sure all the comments that used to exist, including this one, have been ported into the bicep version?

2022-04-19 15:34 UTC, ckittel commented on modules/workloadPoliciesDeployment.bicep
> +        policyDefinitionName: 'fb893a29-21bb-418c-a157-e99480ec364c'
Just a reminder to make these policy definition names either `existing` or in variables so there is a meaningful name for them.

2022-04-19 15:34 UTC, ckittel commented on subscription.bicep
> +param enableAzureDefender bool = true
Let's fix the naming here:  `enableMicrosoftDefenderForCloud` -- we didn't change that last time, but makes sense to do that now.

2022-04-19 15:34 UTC, ckittel commented on subscription.bicep
> +}
Oh, did we only make the defender for containers update in the baseline?  (not asking you to increase scope here -- just asking to make sure we have this tracked on the backlog.)

2022-04-19 16:16 UTC, magrande commented on subscription.bicep
> +param location string = 'centralus'
To avoid using variables I just started by replacing it with 'centralus', but I got this warning:

"A resource location should not use a hard-coded string or variable value. Please use a parameter value, an expression, or the string 'global'"

I could either 

1 - keep the variable 
2 - Use 'Global'
3 - Leave the paramerter

What is the best approach ?

2022-04-19 16:48 UTC, magrande commented on subscription.bicep
> +}
Not 100%  I believe we mentioned we should do it on the baseline too. But not sure if we created a task for the tracking.

2022-04-19 17:01 UTC, magrande commented on modules/subscriptionPolicyAssignment.bicep
> +param notScopes array = []
I should pass it from subscription.bicep here:

'Apply-EnableDefender-Policy'

As we used to pass it in the old subsription.json (line 778)

Added, my bad... sorry

2022-04-19 17:23 UTC, ckittel commented on subscription.bicep
> +}
"do it on the baseline too" -- can you say more about that response?

2022-04-19 17:26 UTC, ckittel commented on subscription.bicep
> +param location string = 'centralus'
`Global` will not work -- these are not `Global` resources.  Either 1 or 3 -- but if you leave it at 3) remove the parts that are not needed (allow list), change its name to match the old name, and add a comment that aligns with the old variable.  Alternatively, just use the variable like it was before, with a comment.

2022-04-19 17:42 UTC, ckittel commented on subscription.bicep
> +                        '/providers/Microsoft.Authorization/roleDefinitions/fb1c8493-542b-48eb-b624-b4c8fea62acd'
Thanks for the update.

2022-04-19 17:44 UTC, ckittel commented on subscription.bicep
> +
Can we make sure that _all_ `existing` stuff sits in a "/*** EXISTING RESOURCES ***/" section of the bicep file like we do in our other content?

2022-04-19 18:04 UTC, magrande commented on modules/networkWatchersPoliciesDeployment.bicep
> +        policyAssignmentEnforcementMode: 'DoNotEnforce'
> The old version had this comment that appears to be lost:
> 
> // Since this RG may be under existing policy control in your subscription, adding this policy as audit-only.
> 
> That's documentation so we don't get asked "why" -- can you make sure all the comments that used to exist, including this one, have been ported into the bicep version?

Done. And checked in other places as well

2022-04-19 18:14 UTC, magrande commented on subscription.bicep
> +    location: empty(networkWatcherRGRegion) ? 'centralus' : networkWatcherRGRegion
Fixed

2022-04-19 18:15 UTC, magrande commented on modules/workloadPoliciesDeployment.bicep
> +        policyDefinitionName: 'fb893a29-21bb-418c-a157-e99480ec364c'
Done in all files

2022-04-19 18:15 UTC, magrande commented on subscription.bicep
> +param enableAzureDefender bool = true
Done

2022-04-19 18:15 UTC, magrande commented on modules/subscriptionPolicyAssignment.bicep
> +param location string = 'centralus'
Right, fixed.

2022-04-19 18:16 UTC, magrande commented on subscription.bicep
> +
Done in all files

2022-04-19 18:37 UTC, magrande commented on subscription.json
> -     */
Done

2022-04-19 18:56 UTC, ckittel commented on subscription.bicep
> +
Can you check **subscriptionPolicyAssignment.bicep** as well

2022-04-19 18:59 UTC, ckittel commented on modules/workloadPoliciesDeployment.bicep
> +        policyDefinitionName: 'fb893a29-21bb-418c-a157-e99480ec364c'
Doesn't look like it was done in **hubsPoliciesDeployment.bicep** or **networkWatchersPoliciesDeployment.bicep** or ****spokesPoliciesDeployment.bicep** -- maybe I'm looking at an old version?  What did you mean by "all files?"

2022-04-19 19:37 UTC, ckittel commented on subscription.bicep
> +@description('Enable Microsoft Defender Standard for Kubernetes Service. Requires Owner or Security Admin role.')
Just so we don't get any questions.  It's known :)

```suggestion
@description('Enable Microsoft Defender for Kubernetes Service. Deprecated, please move to Defender for Containers. Requires Owner or Security Admin role.')
```

2022-04-19 19:38 UTC, ckittel commented on subscription.bicep
> +@description('Enable Microsoft Defender Standard for Container Registry. Requires Owner or Security Admin role.')
Just so we don't get any questions.  It's known :)

```suggestion
@description('Enable Microsoft Defender Standard for Container Registry. Deprecated, please move to Defender for Containers. Requires Owner or Security Admin role.')
```

2022-04-19 20:53 UTC, magrande commented on modules/resourceGroupPolicyAssignment.bicep
> +    name: builtIn ? guid('/providers/Microsoft.Authorization/policyDefinitions/${policyDefintion.name}', resourceGroup().name) : guid(policyDefintion.name, resourceGroup().name)
It's not that easy, I'm going to make some tests and find the best solution

2022-04-19 20:53 UTC, magrande commented on modules/workloadPoliciesDeployment.bicep
> +        policyDefinitionName: 'fb893a29-21bb-418c-a157-e99480ec364c'
Resolved

2022-04-20 15:21 UTC, magrande commented on modules/resourceGroupPolicyAssignment.bicep
> +param policyAssignmentParameters object = {}
Done

2022-04-20 15:22 UTC, magrande commented on modules/resourceGroupPolicyAssignment.bicep
> +    name: builtIn ? guid('/providers/Microsoft.Authorization/policyDefinitions/${policyDefintion.name}', resourceGroup().name) : guid(policyDefintion.name, resourceGroup().name)
We both took care of this :)  Thanks for the pairing session !

2022-04-20 15:22 UTC, magrande commented on modules/resourceGroupPolicyAssignment.bicep
> +        policyDefinitionId: builtIn ? '/providers/Microsoft.Authorization/policyDefinitions/${policyDefintion.name}' : subscriptionResourceId('Microsoft.Authorization/policyDefinitions', policyDefint
Resolved !

2022-04-21 19:51 UTC, ckittel requested changes
I think this is the last batch, almost there!

2022-04-21 19:51 UTC, ckittel commented on modules/workloadPoliciesDeployment.bicep
> +var allowedResourcespolicyAssignmentName = 'a08ec900-254a-4555-9bf5-e42af04b5c5c'
```suggestion
var allowedResourcesPolicyAssignmentName = 'a08ec900-254a-4555-9bf5-e42af04b5c5c'
```

2022-04-21 19:51 UTC, ckittel commented on subscription.bicep
> +module workloadPoliciesDeployment 'modules/workloadPoliciesDeployment.bicep' = {
You're missing depends on here for the custom policies used in this deployment.  You've introduced a race condition by doing so as this deployment could be scheduled before your custom policies have been created.

2022-04-22 15:06 UTC, magrande commented on subscription.bicep
> +}
I redeployed the policies and assignments from scratch and everything looks good

2022-04-22 15:06 UTC, magrande commented on modules/workloadPoliciesDeployment.bicep
> +var allowedResourcespolicyAssignmentName = 'a08ec900-254a-4555-9bf5-e42af04b5c5c'
Usage fixed as well

2022-04-22 15:06 UTC, magrande commented on subscription.bicep
> +    location: networkWatcherRGRegion
Fixed according to old ARM template

2022-04-22 15:07 UTC, magrande commented on docs/deploy/04-subscription.md
> +   az deployment sub create -f subscription.bicep -l centralus -p enableAzureDefender=false enforceAzureDefenderAutoDeployPolicies=false networkWatcherRGRegion="${NETWORK_WATCHER_RG_REGION}"
Fixed

2022-04-22 17:03 UTC, ckittel commented on subscription.bicep
> +    dependsOn:[
```suggestion
    dependsOn: [
```

2022-04-22 17:04 UTC, ckittel approved these changes
LGTM!  Ready to merge if you've completed your testing.  🥳

2022-04-22 17:57 UTC, merged