AKS Baseline regulated - Bicep migration - Networking files
mspnp/aks-baseline-regulated pull request #63
Opened 2022-04-29 14:42 UTC by magrande

closing: #596248

## WHY

we wanted to migrated all ARM json templated for networking to bicep in aks regulated baseline.

## WHAT Changed?

- all network ARM json files are removed
- add new bicep templates for networking (hub/spoke)
- minor streamlining in the subscription deploy doc
- minor bug fix with hard coded policy definition naming convention

## HOW to Test?

you clone the repo, and it is possible to deploy hub and spoke networking Azure resources for regulated using Bicep templates.

2022-04-29 14:43 UTC, ckittel commented on networking/spoke-BU0001A0005-00.bicep
> +@description('Flow Logs deployment')
I know we were going these, but the latest bicep tooling is now upset at using @escription on resources.  We need to go back to using `// ` for these :(

2022-08-24 19:56 UTC, ferantivero commented on networking/spoke-BU0001A0005-00.bicep
> +@description('Flow Logs deployment')
As @ckittel mentioned, this had been an issue (I personally faced) in the past while migrating baseline templates. As @magrande shared in [here](https://github.com/mspnp/aks-baseline-regulated/pull/63#discussion_r861944944) the lint validation seems to be place.

But I can confirm that I deployed these templates without issues, and even added new `description` function calls to resources as part of some additions to this PR. 

All that said @ckittel, I think we could resolve this one in particular for now, and keep an eye in baseline to give some another try in the future to discover the root cause in there.

2022-08-24 19:57 UTC, ckittel commented on networking/spoke-BU0001A0005-00.bicep
> +@description('Flow Logs deployment')
Sounds good, thanks for the followup here!  Marking resolved.

2022-09-02 15:13 UTC, ckittel requested changes
@ferantivero - I was not able to get through the whole review before I had to leave for my PTO today.  I got all of the non-bicep files reviewed and finished `hub-region.v0.bicep`  - When I'm back in the office (6-Sep), I plan on proceeding with the rest of the `.bicep` files.  If you wanted to review what I have here so far, that would be cool.  There are a couple of things you'd forward-apply to `.v1` and `.v2`

2022-09-02 15:13 UTC, ckittel commented on networking/hub-region.v0.bicep
> +  location: location
Any reason this one can't also be made zone-aware?

2022-09-02 15:13 UTC, ckittel commented on networking/hub-region.v0.bicep
> +    }]
Much cleaner, thanks!

2022-09-02 15:13 UTC, ckittel commented on networking/hub-region.v0.bicep
> +      tier: 'Premium'
> Premium

Thx!

2022-09-02 18:09 UTC, ferantivero commented on networking/README.md
> +This is part of the Azure Kubernetes Service (AKS) Baseline Cluster for Regulated Workloads.. For more information see the [readme file in the root](/README.md). These files are the Bicep templates u
got you @ckittel 

done | addressed from afcc744ae68c5210989c56f2d48f3d86840474aa

2022-09-02 18:10 UTC, ferantivero commented on networking/hub-region.v0.bicep
> +  name: 'la-hub-${location}'
yeah probably it has been missing while migrating @ckittel 

done | addressed from c0ba867e42c3b1e1055363f8b1f39da43b6fc674

2022-09-02 18:11 UTC, ferantivero commented on networking/hub-region.v0.bicep
> +  location: location
it is now zone aware @ckittel 

done | addressed from 63050ef123880e7abcf37c85392ca071fe18bc88

2022-09-06 16:09 UTC, ckittel requested changes
Last of the feedback.  Got through the rest of the bicep.

2022-09-13 13:25 UTC, ferantivero commented on networking/hub-region.v0.bicep
> +  name: 'la-hub-${location}-${uniqueString(vnetHub.id)}'
good catch @ckittel 

done | addressed from b818451f97c1461f6e9a34b0293fac57e30c7b3a

2022-09-13 13:26 UTC, ferantivero commented on networking/hub-region.v2.bicep
> +  properties: {
weird added this @ckittel 

done | addressed from 64609b2ee97d0039c27a072a27812e76edd5faf5

2022-09-13 13:32 UTC, ferantivero commented on networking/spoke-BU0001A0005-00.bicep
> +output imageBuilderSubnetResourceId string = imageBuilderVNet.properties.subnets[0].id
now it is @ckittel 

done  | addressed from 4ec6009187a865f5fed00b94a579cb37fac2d5e1

2022-09-13 14:26 UTC, ferantivero commented on networking/spoke-BU0001A0005-01.json
> -                "[subscriptionResourceId('Microsoft.Resources/deployments', 'Apply-Subscription-Spoke-PipUsage-Policies-01')]"
shall we close this one via https://github.com/mspnp/aks-baseline-regulated/pull/63#discussion_r963886199?

2022-09-13 14:32 UTC, ckittel commented on networking/spoke-BU0001A0005-01.json
> -                "[subscriptionResourceId('Microsoft.Resources/deployments', 'Apply-Subscription-Spoke-PipUsage-Policies-01')]"
Can you think of a reason why reversing it would be bad?  The intent was what we had in the former to show "governance" instead of "after thought" -- but it's not a key teachable here, so I'm okay reversing the arrow of dependence here -- as long as we can't think of anything else.  Maybe a comment above the policy that says something that ideally this would have been applied prior to resources being created, including the virtual network, and targeted at the resource group or higher in the hierarchy.

2022-09-13 17:28 UTC, ferantivero commented on networking/spoke-BU0001A0005-01.bicep
> +@description('Enables Azure Key Vault Private Link on cluster vnet.')
changed to use the right description in here @ckittel 

done | addressed from afea6e0d4f4d8c1cbd9a391ba02cf1767a8d94ce

2022-09-13 17:28 UTC, ferantivero commented on networking/spoke-BU0001A0005-01.bicep
> +    location: location
added zone to the pip @ckittel 

done | addressed from a169d8fb8cba38e9ca79961997548a4af3cffd1a

2022-09-13 18:27 UTC, ferantivero commented on networking/spoke-BU0001A0005-01.bicep
> +        clusterVNetId: clusterVNet.id
oh I see, thanks for this sharing this clue @ckittel

2022-09-13 19:02 UTC, ferantivero commented on networking/spoke-BU0001A0005-01.json
> -                "[subscriptionResourceId('Microsoft.Resources/deployments', 'Apply-Subscription-Spoke-PipUsage-Policies-01')]"
I've just reversed this @ckittel, I think while this may enforce earlier the policies, it is reducing readability and probability being a bit more fragile due to the weak dependencies. These potential drawbacks (debatable) should not be more relevant if we are trying to teach 0-day policy enforcement as a best practice or that more robust infrastructure is typically preceded by policy-assignments-first.

2022-09-13 20:20 UTC, ckittel commented on networking/spoke-BU0001A0005-01.json
> -                "[subscriptionResourceId('Microsoft.Resources/deployments', 'Apply-Subscription-Spoke-PipUsage-Policies-01')]"
I really wish there was a weak-reference like $resource.id where it wouldn't do the auto-dependsOn but would still do a resource function conversion.  Oh well.  Yeah, I agree, it's kinda "meh" the way it is now, after the change -- but it's closer to desired end state at least.

2022-09-13 20:25 UTC, ckittel approved these changes
I think this covers it all now, @ferantivero -  I resolved all the feedback. Once you're done with your testing cycle, feel free to merge if good to go.

2022-09-15 16:01 UTC, merged