feat (infra): [cluster-stamp] migrate arm json to bicep v0
mspnp/aks-baseline-regulated pull request #65
Opened 2022-10-13 15:50 UTC by ferantivero

related: #568934

## WHY?

we wanted to migrated all our cluster-stamp from json to bicep lang, so discontinue json as primary iaac templating lang.

## WHAT Changed?

- cluster stamp v0 moved to bicep

## How to Test?

as a user you can now got an equivalent ARM template for the cluster stamp  v0 written in bicep lang.

2022-10-13 19:11 UTC, ckittel requested changes
wow, great work @ferantivero!  This is exciting to see.

2022-10-13 19:11 UTC, ckittel commented on cluster-stamp.bicep
> +@description('The regional load balancer identity used by your Application Gateway instance to acquire access tokens to read ssl certs and secrets from Azure KeyVault.')
```suggestion
@description('The regional load balancer identity used by your Application Gateway instance to acquire access tokens to read certs and secrets from Azure Key Vault.')
```

2022-10-13 19:11 UTC, ckittel commented on cluster-stamp.bicep
> +@description('The secret storage management resource for the aks regulated cluster.')
```suggestion
@description('The secret storage management resource for the AKS regulated cluster.')
```

2022-10-13 19:11 UTC, ckittel commented on cluster-stamp.bicep
> +  // The internet facing Tls certificate to establish https connections between your clients and your regional load balancer
```suggestion
  // The internet facing TLS certificate to establish HTTPS connections between your clients and your regional load balancer
```

2022-10-13 19:11 UTC, ckittel commented on cluster-stamp.bicep
> +@description('Grant the Azure Application Gateway managed identity with key vault secrets user role permissions; this allows pulling secrets from key vault.')
```suggestion
@description('Grant the Azure Application Gateway managed identity with Key Vault secrets user role permissions; this allows pulling secrets from Key Vault.')
```

2022-10-13 19:11 UTC, ckittel commented on cluster-stamp.bicep
> +@description('Grant the Azure Application Gateway managed identity with key vault reader role permissions; this allows pulling frontend and backend certificates.')
```suggestion
@description('Grant the Azure Application Gateway managed identity with Key Vault reader role permissions; this allows pulling frontend and backend certificates.')
```

2022-10-13 19:11 UTC, ckittel commented on cluster-stamp.bicep
> +@description('The aks regulated cluster log analytics workspace.')
```suggestion
@description('The AKS cluster and related resources log analytics workspace.')
```

2022-10-13 19:11 UTC, ckittel commented on cluster-stamp.bicep
> +            id: resourceId(subscription().subscriptionId, targetResourceGroup.name, 'Microsoft.Network/publicIpAddresses', 'pip-BU0001A0005-00')
Can you pull this in as an `existing` resource at the top?  I know the AKS baseline doesn't do this, (but should :))

2022-10-13 19:11 UTC, ckittel commented on cluster-stamp.bicep
> +    scope: subscriptionResourceId('Microsoft.Resources/resourceGroups', resourceGroup().name)
All of these policy assignments, I think should just be 

```suggestion
    scope: resourceGroup()
```

for scope.

2022-10-13 19:11 UTC, ckittel commented on docs/deploy/09-aks-cluster.md
> +   az deployment group create -g rg-bu0001a0005 -f cluster-stamp.bicep -p targetVnetResourceId=${RESOURCEID_VNET_CLUSTERSPOKE} clusterAdminAadGroupObjectId=${AADOBJECTID_GROUP_CLUSTERADMIN} k8sContro
You changed params (like regions) to not have defaults.  Planning on updating that here and in the params file as well?

2022-10-13 19:11 UTC, ckittel commented on docs/deploy/09-aks-cluster.md
> +   > :eyes: If you're curious to see what changed in the cluster stamp, [view the diff](https://diffviewer.azureedge.net/?l=https://raw.githubusercontent.com/mspnp/aks-baseline-regulated/main/cluster
heh :)  Technically the correct thing to do.

2022-10-14 16:27 UTC, ferantivero commented on cluster-stamp.bicep
> +var crName = 'craks${subRgUniqueString}'
I think CAF propose  `cr` and looks better aligned with its resource type. The reason behind is propositional and open to restore the missing `a` as-in azure.

2022-10-14 16:44 UTC, ferantivero commented on cluster-stamp.bicep
> +    name: 'agw-ingress-incluster-aks-ingress-contoso-com-tls'
this is a proposal to normalize different namings we have currently out there (`appgw`, `apw`, others) with a TLA CAF-ish `agw`.

Open to normalize this to our reviewer's preference.

2022-10-14 16:47 UTC, ferantivero commented on cluster-stamp.bicep
> +  name: 'law-${clusterName}'
yeah, just trying to propose as many CAF-ish TLA as possible to normalize our namings especially when the resource type contains three words with exception when the resource type is two workds (`cr`, `mc`, `xyz`).

2022-10-14 17:00 UTC, ferantivero commented on docs/deploy/09-aks-cluster.md
> +   az deployment group create -g rg-bu0001a0005 -f cluster-stamp.bicep -p targetVnetResourceId=${RESOURCEID_VNET_CLUSTERSPOKE} clusterAdminAadGroupObjectId=${AADOBJECTID_GROUP_CLUSTERADMIN} k8sContro
Im just restore missing default values. This should remain the same if I am not mistaken.

2022-10-14 17:03 UTC, ferantivero commented on cluster-stamp.bicep
> +param geoRedundancyLocation string
laser focus badge achieved @ckittel 

done | addressed from e368763695495ed298ff82ae81033c3e3d1a40f6

2022-10-14 17:04 UTC, ferantivero commented on cluster-stamp.bicep
> +param jumpBoxCloudInitAsBase64 string = '10.200.0.0/26'
slipped off machine detector badge achieved @ckittel 

done |   addressed from a45abb238a6d92178e139dc1e04e567ef0a70185

2022-10-14 17:08 UTC, ferantivero commented on cluster-stamp.bicep
> +@description('The control plane identity used by the cluster.')
learn by heart all my comments and never forget them badge achieved @ckittel, really that was really hard to detect. Appreciate you are the one reviewing  this one.

done | addressed from c0f0d0e3c82de612752ff47ed855855e99219576

2022-10-14 18:56 UTC, ferantivero commented on cluster-stamp.bicep
> +}
good catch @ckittel

done | addressed from 16195350143b5d9a6de0bca50bf3388a3513d9f1

2022-10-14 18:58 UTC, ferantivero commented on cluster-stamp.bicep
> +resource targetResourceGroup 'Microsoft.Resources/resourceGroups@2021-04-01' existing = {
alright changed @ckittel 

done | addressed from 58838dcb92479bdf693311099c9e33a915c495ca and just proposing this another e64c830f2931cff605043b69d945d1fabda046cf change (please don't hesitate in asking to revert or change to something more appealing)

2022-10-14 19:22 UTC, ckittel commented on cluster-stamp.bicep
> +    name: 'agw-ingress-incluster-aks-ingress-contoso-com-tls'
This comment isn't about the prefix, this is about the rest of the secret name relative to what it was before.

2022-10-14 19:23 UTC, ckittel commented on cluster-stamp.bicep
> +resource targetResourceGroup 'Microsoft.Resources/resourceGroups@2021-04-01' existing = {
looks good!

2022-10-14 19:26 UTC, ckittel commented on cluster-stamp.bicep
> +            id: resourceId(subscription().subscriptionId, targetResourceGroup.name, 'Microsoft.Network/publicIpAddresses', 'pip-BU0001A0005-00')
Looks good!

2022-10-14 19:27 UTC, ckittel commented on docs/deploy/09-aks-cluster.md
> +   az deployment group create -g rg-bu0001a0005 -f cluster-stamp.bicep -p targetVnetResourceId=${RESOURCEID_VNET_CLUSTERSPOKE} clusterAdminAadGroupObjectId=${AADOBJECTID_GROUP_CLUSTERADMIN} k8sContro
Indeed.  Thanks

2022-10-14 19:28 UTC, ferantivero commented on cluster-stamp.bicep
> +        }
and it is now restored @ckittel 

done | addressed from d03bb31aff1eacd8f2280c939ff00da149cddb4f

2022-10-14 19:34 UTC, ckittel commented on cluster-stamp.bicep
> +var crName = 'craks${subRgUniqueString}'
Based on convo, return to `acr`

2022-10-14 19:39 UTC, ckittel commented on cluster-stamp.bicep
> +    name: 'agw-ingress-incluster-aks-ingress-contoso-com-tls'
Set to: `agw-ingress-internal-aks-ingress-contoso-com-tls`

2022-10-14 19:57 UTC, ferantivero commented on cluster-stamp.bicep
> +            id: resourceId(subscription().subscriptionId, targetResourceGroup.name, 'Microsoft.Network/publicIpAddresses', 'pip-BU0001A0005-00')
good idea @ckittel 

done | addressed from cc3369232c11c193021af4f780bd04f4d587fca3

2022-10-14 19:58 UTC, ferantivero commented on cluster-stamp.bicep
> +}
based on our offline convo we are going full rbac here by adding also the role assigns for ingress controller.

2022-10-14 19:59 UTC, ferantivero commented on cluster-stamp.bicep
> +        availabilityZones: pickZones('Microsoft.ContainerService', 'managedClusters', location, 3)
based on our offline convo, managed clusters resource type doesn't allow zone so we have to be careful and ensure this returns a valid array with values for zones. If not, we want to use another type (i.e. VMSS) or return to hardcoded zones.

2022-10-14 20:07 UTC, ferantivero commented on cluster-stamp.bicep
> +    name: 'agw-ingress-incluster-aks-ingress-contoso-com-tls'
combined @ckittel 

done | addressed from 7f8872da61d245cc034d8ff310a257e5c2f181f8

2022-10-14 20:08 UTC, ferantivero commented on cluster-stamp.bicep
> +    zoneRedundancy: 'Disabled'
based on our offline convo, we are testing this as well.

2022-10-14 20:08 UTC, ferantivero commented on cluster-stamp.bicep
> +var crName = 'craks${subRgUniqueString}'
yup and changed @ckittel 

done | addressed from 300ae00bc8029a353683fa1061f337f31204bee7

2022-10-14 20:12 UTC, ckittel commented on cluster-stamp.bicep
> +}
@ferantivero as part of this, please make sure that the App GW depends on this role assignment and not just Key Vault.

2022-10-14 20:15 UTC, ckittel commented on cluster-stamp.bicep
> +    scope: subscriptionResourceId('Microsoft.Resources/resourceGroups', resourceGroup().name)
This is for all of them, not just this one.

2022-10-14 20:19 UTC, ferantivero commented on cluster-stamp.bicep
> +    scope: subscriptionResourceId('Microsoft.Resources/resourceGroups', resourceGroup().name)
you got it @ckittel 

done | addressed from c8782f5faae65ac6e1f80143e44a987223909159

2022-10-14 20:28 UTC, ferantivero commented on cluster-stamp.bicep
> +}
changed to full rbac @ckittel 

done | addressed from 54df66b9fdac83488ef48e10df91d2fb0e415ca2

2022-10-14 21:22 UTC, ckittel commented on cluster-stamp.bicep
> +}
Looks good!

2022-10-18 21:51 UTC, ferantivero commented on cluster-stamp.bicep
> +    scope: subscriptionResourceId('Microsoft.Resources/resourceGroups', resourceGroup().name)
not the exact issue that has been raised here @ckittel , but interestingly enough I faced issues assigning a scope to these policy assignments. 

removed them from ca1e1848c2b09042140742a680de82efac15348f and leaving a comment in here in case it spark some ideas.

2022-10-20 21:51 UTC, ferantivero commented on cluster-stamp.bicep
> +    scope: subscriptionResourceId('Microsoft.Resources/resourceGroups', resourceGroup().name)
based on our offline chat/checks around the policies scope, I'm resolving this one as Im the one who re-open this.

2022-10-20 22:25 UTC, ferantivero commented on cluster-stamp.bicep
> +        availabilityZones: pickZones('Microsoft.ContainerService', 'managedClusters', location, 3)
changed to VMSS @ckittel, manage clusters was not the proper one as discussed and resulted in an empty array.

done | addressed from 39c735f6596aea54c0378110d03fd6880ac3af8c

2022-10-21 19:34 UTC, ferantivero commented on cluster-stamp.bicep
> +    zoneRedundancy: 'Disabled'
tested it @ckittel, and worked ok.

done | addressed from ae8ae34d2cd4f3b52791c56c2c3a7858c1bf255a

2022-10-21 19:44 UTC, ckittel approved these changes
LGTM!  Thank you @ferantivero 

(I can't seem to access my old review to mark items resolved, but I spotted them here.  Good to go.)

2022-10-21 20:17 UTC, merged