feat (workload identity): [ingress] migrate pod to workload indentiy
mspnp/aks-baseline-regulated pull request #66
Opened 2022-10-28 20:24 UTC by ferantivero

closes: #24723

## WHY?

we do want to move all our aks baseline from aad pod identity manually installed or via add-ons to workload identity.

## WHAT changed?

- migrate from AAD Pod Identity to Azure Workload Identity (Add on)
- minor bug fixings 

## HOW to test?

as a user you can now clone the aks regulated baseline repository, follow the instructions and the cluster stamp v2 will create federated credentials identity subject to the nginx ingress controller service account and enable the workload identity add on in the aks regulated cluster.

you can deploy the cluster end to end and validate it is working as expected.

2022-12-06 21:27 UTC, ckittel requested changes

2022-12-06 21:27 UTC, ckittel commented on cluster-manifests/ingress-nginx/akv-tls-provider.yaml
> +    tenantId: KEYVAULT_TENANT
Please move to `tenantID` as per the CRD.

2022-12-06 21:27 UTC, ckittel commented on cluster-stamp.bicep
>      kvMiIngressControllerSecretsUserRole_roleAssignment
Do we instead want the federated identity here?  Speaking of, where is that created?  I would have expected that to be here in this bicep file.

2022-12-06 21:27 UTC, ckittel commented on docs/deploy/01-prerequisites.md
> +   # When all say "Registered" then re-register the AKS and related resource providers
```suggestion
   # When all say "Registered" then re-register the AKS and related resource providers
```

2022-12-06 21:27 UTC, ckittel commented on docs/deploy/02-ca-certificates.md
> +   AKS_INGRESS_CONTROLLER_CERTIFICATE_BASE64=$(cat ingress-internal-aks-ingress-contoso-com-tls.crt | base64 | tr -d '\n')
Should we open a PR just to fix this issue?  Or do you want to keep it included in here?

2022-12-06 21:27 UTC, ckittel commented on docs/deploy/09-aks-cluster.md
> -   **cluster-stamp.v2.json** is a _tiny_ evolution of the **cluster-stamp.bicep** ARM template you literally just deployed in the step above. Because we are using Azure AD Pod Identity v1 as a Micros
So great to see this gone.  <3

2022-12-06 21:27 UTC, ckittel commented on cluster-stamp.bicep
> +    oidcIssuerProfile: {
I didn't see the federated identity get created or anything here.  I'm confused a bit at the lack of the `federatedIdentityCredentials` resource.

2022-12-07 02:02 UTC, ferantivero commented on cluster-stamp.bicep
> +    oidcIssuerProfile: {
yeah, my bad @ckittel, I've got rid of it when I last minute removed the `v2` bicep. 

done | addressed 30cbb5f9b4aeae119784ed7f7506c93086b324b4

2022-12-07 02:03 UTC, ferantivero commented on docs/deploy/02-ca-certificates.md
> +   AKS_INGRESS_CONTROLLER_CERTIFICATE_BASE64=$(cat ingress-internal-aks-ingress-contoso-com-tls.crt | base64 | tr -d '\n')
I think it is fine to keep it here as long it doesn't required more changes.

2022-12-07 02:03 UTC, ferantivero commented on cluster-stamp.bicep
>      kvMiIngressControllerSecretsUserRole_roleAssignment
I think that ^ could result in circular dependency due to the federated identity issuer.

Yeah, it was but that got rid of when I last minute removed the v2. [It is now back](https://github.com/mspnp/aks-baseline-regulated/pull/66#discussion_r1041673890).

2022-12-07 02:04 UTC, ferantivero commented on cluster-manifests/ingress-nginx/akv-tls-provider.yaml
> +    tenantId: KEYVAULT_TENANT
you got it @ckittel,

done | addressed from 864d745d0facec722f18b8411fb05be524576aa3

2022-12-07 02:06 UTC, ferantivero commented on docs/deploy/09-aks-cluster.md
> -   **cluster-stamp.v2.json** is a _tiny_ evolution of the **cluster-stamp.bicep** ARM template you literally just deployed in the step above. Because we are using Azure AD Pod Identity v1 as a Micros
actually this was based on a sync up I had with Fred.

so kudos to @v-fearam

2022-12-07 14:18 UTC, ckittel approved these changes
Everything looks great.  I do have one question here... it's optional to change, and figured I'd let you decide.

2022-12-07 14:18 UTC, ckittel commented on cluster-stamp.bicep
> +
In the baseline, we simply [nested this](https://github.com/mspnp/aks-baseline/blob/794345686063239795219723fe222af0e0ce1562/cluster-stamp.bicep#L1438).  Any reason to keep it out, and separated by a different resource even?  What you have is technically accurate, but would be ideal if it was aligned to the baseline's structure/naming to minimize a difference.  Unless it's better separated?

2022-12-12 12:23 UTC, ferantivero commented on cluster-stamp.bicep
> +
you got it @ckittel, yes I agree to keep it nested as this is not required outside.

done | addressed from c978c6d0fdb1e7f80140e0e031a4875ad0ada6ee

2022-12-12 14:47 UTC, ckittel commented on cluster-stamp.bicep
> +
Thx!

2022-12-13 16:23 UTC, merged