ACR/Key Vault deploy relocation and moving to Flux extension
mspnp/aks-baseline-regulated pull request #71
Opened 2022-12-13 16:58 UTC by v-fearam

## WHY?

we do want to move all our aks baseline from flux manually installed to Flux extension add-on.

## WHAT changed?

- ACR/Azure Key Vault/Some Identities are deployed independently and before the cluster.
- The ACR is populated before the cluster deploy and the flux files customized before the Flux extension is deployed. 

## HOW to test?

as a user you can now clone the aks regulated baseline repository, follow the instructions.

You can deploy the cluster end to end and validate it is working as expected.

2022-12-13 17:25 UTC, v-fearam commented on cluster-manifests/ingress-nginx/deployment.yaml
> +  annotations:
This is not needed. Fernando makes it work, but the documentation official documentation point this change out, that why it was included.
https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access#configure-workload-identity (dot 4)

2022-12-13 17:27 UTC, v-fearam commented on cluster-stamp.bicep
> +resource fic 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2022-01-31-preview' = {
The identity was created in advance because some files need to be customized before cluster stamp (flux execution).
The Federated identity need to be keep here because of the issuer (The cluster)

2022-12-13 17:29 UTC, v-fearam commented on docs/deploy/10-pre-bootstrap.md
> +
Customizations before cluster depoy.

2022-12-15 21:00 UTC, ckittel requested changes
I only got part of the way through this review @v-fearam.  A good chunk of it is "timing/organization" so, wanted to pause here so I don't overload with a lot of feedback.  Can we sync on the general themes here and maybe you can take swipe at getting them moved into this direction a bit more?

2022-12-15 21:00 UTC, ckittel commented on README.md
> +* [ ] [Prepare for cluster deploy](./docs/deploy/10-pre-bootstrap.md). The ACR is populated, Quarantine & import all bootstrap images,  and some files are customized.
In the baseline, we called this step "Prep for cluster bootstrapping" and I think that would make sense here as well. Bootstrapping is a term we have worked hard to get into our content and into the lingo around this, I'd do what you can here to brand this part akin to what we do in the baseline.

2022-12-15 21:00 UTC, ckittel commented on README.md
> +* [ ] [Jump box access and Flux are validated](./docs/deploy/12-jumpbox-addon-validation.md).
We called this "Validate cluster bootsrapping" in the baseline.  I'd propse something similar here.  "Validate cluster access and bootstrapping."

The format of these are verb + noun.  "Jump box access" is noun + verb anyhow, so we'd want to change that anyhow

2022-12-15 21:00 UTC, ckittel commented on README.md
>  Deploy the Azure resources that make up the primary runtime components of this architecture; the AKS cluster itself, jump box, Azure Container Registry, Azure Application Gateway, and Azure Key Vault
I can't leave a comment on the line, since it didn't change.  But at the top of this file, please make the "In-cluster OSS components" read out like they do in the baseline.  https://github.com/mspnp/aks-baseline#in-cluster-oss-components  Where we call out what is coming through an add-on or extension.

2022-12-15 21:00 UTC, ckittel commented on README.md
> -* [ ] [Quarantine & import all bootstrap images](./docs/deploy/10-pre-bootstrap.md) to Azure Container Registry.
We will want to make sure we're keeping "Quarantine" as well as a visible title/term in the step that does it, if possible.

2022-12-15 21:00 UTC, ckittel commented on README.md
>  Deploy the Azure resources that make up the primary runtime components of this architecture; the AKS cluster itself, jump box, Azure Container Registry, Azure Application Gateway, and Azure Key Vault
I'd update this text to incorporate some of the wording from the baseline.

2022-12-15 21:00 UTC, ckittel commented on cluster-manifests/flux-system/resource-quota.yaml
> -apiVersion: v1
Any reason why we got rid of this?  It might need to change, but not sure it should go away?  Think about it a bit and see if it would make sense to keep it around in v2/extension land.  It might be a good idea in a regulated cluster to keep.

2022-12-15 21:00 UTC, ckittel commented on cluster-manifests/ingress-nginx/deployment.yaml
> +  annotations:
I'm not sure I understand what you mean "This is not needed" but it's in here.  Can you clarify if you're going to change this. If you're asking a question. If @ferantivero should be pinged.  Not following the intent of this comment, sorry :(

2022-12-15 21:00 UTC, ckittel commented on docs/deploy/09-pre-cluster-stamp.md
> +Now that the [hub-spoke network is provisioned](./04-networking.md), the next step in the [AKS Baseline for Regulated workloads reference implementation](./) is preparing what your AKS cluster should
the prior step is 4?

2022-12-15 21:00 UTC, ckittel commented on docs/deploy/10-pre-bootstrap.md
>  # Prepare to bootstrap the cluster
How do we have two pages with bascially the same title?  This on the prior one.

Any reason we can't just integrate the work on the prior p[age into this one?  The baseline combines both the deployment of the acr resources and the importing of the images.  I'd say we do the same thing here.

2022-12-15 21:00 UTC, ckittel commented on docs/deploy/10-pre-bootstrap.md
>     az acr import --source quarantine/fluxcd/kustomize-controller:v0.8.1 -r $ACR_NAME_QUARANTINE -t live/fluxcd/kustomize-controller:v0.8.1 -n $ACR_NAME && \
Why are we still importing flux?

2022-12-15 21:00 UTC, ckittel commented on docs/deploy/10-pre-bootstrap.md
>     az acr import --source ghcr.io/fluxcd/kustomize-controller:v0.8.1 -t quarantine/fluxcd/kustomize-controller:v0.8.1 -n $ACR_NAME_QUARANTINE && \
Still importing flux here?

2022-12-15 21:00 UTC, ckittel commented on docs/deploy/10-pre-bootstrap.md
> +   At this point we have the Azure Key Vault deployed and it is before deploying Flux configuration.
> At this point we have the Azure Key Vault deployed and it is before deploying Flux configuration.

I don't know what this sentence is asking the user to do or letting the user know.  This wasn't in the original text, so curious what the intent was to add this.  Can you clarify?

2022-12-15 21:00 UTC, ckittel commented on docs/deploy/10-pre-bootstrap.md
> +1. Push those three commits to your repo.
Three?  I only see two.

2022-12-15 21:00 UTC, ckittel commented on docs/deploy/11-aks-cluster.md
>  1. Obtain the Azure Key Vault details and give the current user permissions and network access to import certificates.
Almost feeling like we should have done this back in the bootstrapping steps somewhere.  Otherwise, we run into an issue where we're referencing a thing that doesn't actually exist in the bootstrapping config.  Thoughts on pulling this forward?

2022-12-15 21:00 UTC, ckittel commented on docs/deploy/12-jumpbox-addon-validation.md
> +Your cluster was deployed with Azure Policy and Flux extension. You'll execute some commands to show how those add-ons are manifesting itself in your cluster.
To be clear, flux isn't an add-on, and we want to make sure we don't accidentally call it that.  flux is an extension, and that matters because they have a different lifecycle than an add-on.

2022-12-15 21:00 UTC, ckittel commented on docs/deploy/12-jumpbox-addon-validation.md
> +Now that [the AKS cluster](./11-aks-cluster.md) has been deployed, and your [bootstrapping images have passed through quarantine](./10-pre-bootstrap.md), the next step is to Jump box access and Flux
our goal is to continue to reference it as GitOps here, because we (MSFT) might choose a different orchestration tool at some point, i'd try to bring that concept back into this sentence and page title

2022-12-15 21:00 UTC, ckittel commented on docs/deploy/12-jumpbox-addon-validation.md
> +# Jump box access and Flux are validation
the filename is weird here, what is a "jumpbox addon?"

2022-12-16 10:09 UTC, v-fearam commented on cluster-manifests/ingress-nginx/deployment.yaml
> +  annotations:
"This is not needed" means "it works anyway without doing this change in our context". The csi-workflow identity documentation said that it is needed to be changed. The question is 'keep or deleted'? , my option was keep and honor the official documentation, but I'm open to opinions.

2022-12-16 17:52 UTC, ckittel commented on cluster-manifests/ingress-nginx/deployment.yaml
> +  annotations:
Based on the upstream documentation, and the fact that ingress-nginx is not a _direct_ consumer of Workload Identity, these annotations/labels should not be applied here.  Please remove.

2022-12-16 18:04 UTC, ckittel commented on cluster-manifests/flux-system/resource-quota.yaml
> -apiVersion: v1
and also LimitRanges

2022-12-16 18:11 UTC, ckittel commented on pre-cluster-stamp.bicep
> +}
Move last two back to the cluster-stamp.bicep file.

2022-12-16 18:15 UTC, ckittel commented on pre-cluster-stamp.bicep
> +resource kv 'Microsoft.KeyVault/vaults@2022-07-01' = {
Please bring over the diagnostics settings (and any alerts ?) so that this is "ready to use" after deployment here.  No unmonitored resources in regulated environments.

2022-12-16 18:22 UTC, ckittel commented on pre-cluster-stamp.bicep
> +resource miIngressController 'Microsoft.ManagedIdentity/userAssignedIdentities@2022-01-31-preview' = {
Please also bring over the role assignment between this at AKV from the cluster-stamp.bicep file.

2022-12-16 18:28 UTC, ckittel commented on networking/hub-region.v2.bicep
> -              name: 'install-flux'
Good catch, we need to also remove from: https://github.com/mspnp/aks-jumpbox-imagebuilder/blob/a1422519d8910a6af24db69b235ac787c611d2fc/azuredeploy.bicep#L203

2022-12-22 11:14 UTC, v-fearam commented on networking/hub-region.v2.bicep
> -              name: 'install-flux'
https://github.com/mspnp/aks-jumpbox-imagebuilder/pull/15

2022-12-22 11:15 UTC, v-fearam commented
Please do a new pass when it works for you

2022-12-28 17:36 UTC, ckittel requested changes
Dang, that looks really good.  Most of my comments here are small (and come with suggestions.)

2022-12-28 17:36 UTC, ckittel commented on docs/deploy/11-validate-cluster-access-and-bootstrapping.md
>  While the following process likely would be handled via your deployment pipelines, we are going to use this opportunity to demonstrate cluster management access via Azure Bastion, and show that your
```suggestion
Because the cluster is private, your cluster cannot be directly accessed locally. You'll validate controlled jump box access for direct ops against the cluster if needed.
```

2022-12-28 17:36 UTC, ckittel commented on docs/deploy/11-validate-cluster-access-and-bootstrapping.md
> +### AKS access validation
```suggestion
### Bootstrapping results validation
```

2022-12-28 17:36 UTC, ckittel commented on docs/deploy/11-validate-cluster-access-and-bootstrapping.md
> +Your cluster was deployed with Azure Policy and Flux extension. You'll execute some commands to show how those add-ons are manifesting itself in your cluster.
```suggestion
Your cluster was deployed with Azure Policy and the Flux GitOps extension. You'll execute some commands to show how those are manifesting itself in your cluster.
```

2022-12-28 17:36 UTC, ckittel commented on docs/deploy/11-validate-cluster-access-and-bootstrapping.md
> +1. _From your Azure Bastion connection_, bootstrap Flux Validation.
```suggestion
1. _From your Azure Bastion connection_, validate bootstrapping.
```

2022-12-28 17:36 UTC, ckittel commented on docs/deploy/11-validate-cluster-access-and-bootstrapping.md
>     Validate that Flux has been bootstrapped.
```suggestion
   Validate that the Flux extension has bootstrapped your cluster.
```

2022-12-28 17:36 UTC, ckittel commented on docs/deploy/11-validate-cluster-access-and-bootstrapping.md
> +   # You must see namespaces created by flux like a0005-i
~~~suggestion
   ```bash
   kubectl get namespaces
   ```
   
   You should see namespaces created as described your manifest files, such as `a0005-i`.
   
   ```output
~~~

2022-12-28 17:36 UTC, ckittel commented on docs/deploy/11-validate-cluster-access-and-bootstrapping.md
>  There is a subnet allocated in this reference implementation called `snet-management-agents` specifically for your build agents to perform unattended, "last mile" deployment, and configuration needs
```suggestion
## Configuration needs outside of GitOps

There is a subnet allocated in this reference implementation called `snet-management-agents` specifically for your build agents to perform unattended, "last mile" deployment, and configuration needs for your cluster. There is no compute deployed to that subnet, but typically this is where you'd put in a Virtual Machine Scale Set as a [GitHub Action Self-Hosted Runner](https://docs.github.com/actions/hosting-your-own-runners/about-self-hosted-runners) or [Azure DevOps Self-Hosted Agent Pool](https://learn.microsoft.com/azure/devops/pipelines/agents/scale-set-agents?view=azure-devops). This compute should be a hardened, minimal installation set, and monitored. Just like a jump box, this compute will span two distinct security zones; in this case, unattended, externally managed GitHub Workflow definitions and your cluster.
```

2022-12-28 17:36 UTC, ckittel commented on docs/deploy/11-validate-cluster-access-and-bootstrapping.md
>  In summary, there should be a stated objective in your team that routine processes (especially bootstrapping new clusters), are never performed by a human via direct access tools `kubectl` -- _Zero-k
Below in the "GitOps configuration" section (can't leave a comment there, sorry).

* remove "Built-in [bootstrapping support](https://fluxcd.io/docs/installation/#bootstrap)"
* remove last three items (all start with "Flux's ")
* add "Additional flux controllers like Helm. These are explicitly disabled to reduce surface area on the extension in the regulated cluster.  Enable only those controllers you need from within the `mcFlux_extension` resource in your ARM template."

Also add

2022-12-28 17:36 UTC, ckittel commented on docs/deploy/11-validate-cluster-access-and-bootstrapping.md
>     If this is the first time you've used Azure Bastion, here is a detailed walk through of this process.
below (a ways) is a output section that still shows 1.22 for versions, can you please update that to 1.24 (or whatever version we're on here)

2022-12-28 17:36 UTC, ckittel commented on docs/deploy/12-workload.md
>     > :notebook: See [Azure Architecture Center guidance for PCI-DSS 3.2.1 Requirement 2.2.1 in AKS](https://learn.microsoft.com/azure/architecture/reference-architectures/containers/aks-pci/aks-pci-n
Need to add the 🛑 to this step above.  That indicates a manual change is needed.

2022-12-28 17:36 UTC, ckittel commented on docs/deploy/12-workload.md
> +This point in the steps marks a significant transition in roles and purpose. At this point, you have a [AKS cluster that is deployed in an architecture that will help your compliance needs](./10-aks-
```suggestion
This point in the steps marks a significant transition in roles and purpose. At this point, you have a [AKS cluster that is deployed in an architecture that will help your compliance needs](./10-aks-cluster.md) and is bootstrapped with core tooling you feel are requirements for your solution, all managed via the Flux extension. You've got a cluster without any business workloads.
```

2022-12-28 17:36 UTC, ckittel commented on pre-cluster-stamp.bicep
> +param aksIngressControllerCertificate string
I know it wasn't like this before, but can you add...
```suggestion
@minLength(35)
param aksIngressControllerCertificate string
```

2022-12-28 17:36 UTC, ckittel commented on pre-cluster-stamp.bicep
> +@description('Grant the Ingress Controller managed identity with Key Vault secrets user role permissions; this allows pulling secrets from Key Vault.')
```suggestion
@description('Grant the ingress controller\'s managed identity with Key Vault secrets user role permissions; this allows pulling secrets from Key Vault.')
```

2022-12-28 17:36 UTC, ckittel commented on pre-cluster-stamp.bicep
> +@description('Grant the Ingress Controller managed identity with Key Vault reader role permissions; this allows pulling frontend and backend certificates.')
```suggestion
@description('Grant the ingress controller\'s managed identity with Key Vault reader role permissions; this allows pulling frontend and backend certificates.')
```

2022-12-28 17:36 UTC, ckittel commented on cluster-stamp.bicep
> +  name: 'mi-${clusterName}-ingresscontroller'
To be consistent with your other references

```suggestion
  scope: resourceGroup()
  name: 'mi-${clusterName}-ingresscontroller'
```

2022-12-28 17:36 UTC, ckittel commented on cluster-stamp.bicep
> +
This one is in the "SUBSCRIPTION" resources section, can you move up into the RG section?  Also, you should be able to build the reference to this secret like subnets are done under vnets.  So, as a child of the keyvault.

2022-12-28 17:36 UTC, ckittel commented on cluster-stamp.bicep
> +resource fic 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2022-01-31-preview' = {
```suggestion
@description('Workload identity service account federation for the ingress controller\'s identity which is used to acquire access tokens to read TLS certs from Azure Key Vault.')
resource fic 'Microsoft.ManagedIdentity/userAssignedIdentities/federatedIdentityCredentials@2022-01-31-preview' = {
```

2022-12-28 17:36 UTC, ckittel commented on cluster-stamp.bicep
> +    issuer: mc.properties.oidcIssuerProfile.issuerURL
Because this depends on the cluster, can you move this lower in the file?

2022-12-28 17:43 UTC, ckittel commented on cluster-stamp.bicep
> +    issuer: mc.properties.oidcIssuerProfile.issuerURL
Also, can you make this a dependency for flux?  That way this is for sure deployed before flux starts doing its thing.

2022-12-29 20:02 UTC, v-fearam commented on docs/deploy/11-validate-cluster-access-and-bootstrapping.md
>     If this is the first time you've used Azure Bastion, here is a detailed walk through of this process.
I updated to the current cluster version, 1.23.12.

2022-12-29 20:08 UTC, ckittel requested changes

2022-12-29 20:08 UTC, ckittel commented on azuredeploy.parameters.prod.json
> +      "value": "[Your cluster will be bootstrapped from this branch in the identified git repo.]"
Thanks for adding these, but you still have `geoRedundancyLocation` in here -- please fully align to the new template parameters.

2022-12-29 20:08 UTC, ckittel commented on cluster-stamp.bicep
> +  resource kvsAppGwIngressInternalAksIngressTls 'secrets' existing = {
```suggestion

  resource kvsAppGwIngressInternalAksIngressTls 'secrets' existing = {
```

2022-12-29 20:08 UTC, ckittel commented on cluster-stamp.bicep
> +      'notification-controller.enabled': 'false'
I had an issue in the baseline today where I needed to set the notification-controller to true to work around some nasty error logs in the flux controller logs.  Did you notice anything like that?

2022-12-29 20:08 UTC, ckittel commented on docs/deploy/11-validate-cluster-access-and-bootstrapping.md
> +   aks-npsystem-26621167-vmss000002      Ready    agent   20m   v1.23.12
```suggestion
   aks-npinscope01-26621167-vmss000000   Ready    agent   20m   v1.23.x
   aks-npinscope01-26621167-vmss000001   Ready    agent   20m   v1.23.x
   aks-npooscope01-26621167-vmss000000   Ready    agent   20m   v1.23.x
   aks-npooscope01-26621167-vmss000001   Ready    agent   20m   v1.23.x
   aks-npsystem-26621167-vmss000000      Ready    agent   20m   v1.23.x
   aks-npsystem-26621167-vmss000001      Ready    agent   20m   v1.23.x
   aks-npsystem-26621167-vmss000002      Ready    agent   20m   v1.23.x
```

2022-12-29 20:08 UTC, ckittel commented on docs/deploy/11-validate-cluster-access-and-bootstrapping.md
> +Additional flux controllers like Helm. These are explicitly disabled to reduce surface area on the extension in the regulated cluster. Enable only those controllers you need from within the mcFlux_ex
```suggestion
* Additional Flux controllers like Helm. These additional controllers are explicitly disabled to reduce surface area on the extension in the regulated cluster. Enable only those controllers you need from within the `mcFlux_extension` resource in your ARM template.
```

2022-12-29 20:40 UTC, v-fearam commented on cluster-stamp.bicep
> +      'notification-controller.enabled': 'false'
I don't have a deploy running now. I deleted the latest test. Nothing that I caught my attention. But I didn't put enough  attention to logs after starting working end to end.

2022-12-29 20:46 UTC, ckittel commented on cluster-stamp.bicep
> +      'notification-controller.enabled': 'false'
if it's working end-to-end, that's fine with me.  Marking resolved.

2022-12-29 22:54 UTC, ferantivero reviewed
nicely done @v-fearam just a few comments to discuss more than to request changes. After discussing I would like to do a quick follow up and request a change or two if needed.

2022-12-29 22:54 UTC, ferantivero commented on cluster-stamp.bicep
> +resource kvsAppGwIngressInternalAksIngressTls 'Microsoft.KeyVault/vaults/secrets@2021-11-01-preview' existing = {
I think I get why some resources are being moved around while I'm still trying to get my head around why this cert is being created earlier.

Any particular reason? Isn't this owned by the in-cluster ingress and configured in the appgw?

2022-12-29 22:54 UTC, ferantivero commented on cluster-stamp.bicep
> +@description('Your cluster will be bootstrapped from this git repo.')
```suggestion
@description('The git repo https url with the desire state for the AKS regulated cluster')
```

2022-12-29 22:54 UTC, ferantivero commented on cluster-stamp.bicep
> +@description('Your cluster will be bootstrapped from this branch in the identified git repo.')
```suggestion
@description('The branch name from the git repo with the desire state for the AKS regulated cluster')
```

2022-12-29 22:54 UTC, ferantivero commented on docs/deploy/09-pre-cluster-stamp.md
> +   az deployment group create -g rg-bu0001a0005 -f pre-cluster-stamp.bicep -p targetVnetResourceId=${RESOURCEID_VNET_CLUSTERSPOKE} aksIngressControllerCertificate=${INGRESS_CONTROLLER_CERTIFICATE_BAS
shouldn't we commit the desire state files post cluster deployment instead of this pre because of the flux extension, methinks.

While I'm not requesting such a change a this point, I would like to discuss wether this alternative had been considered.

So leaving this comment as a bookmark.

2022-12-29 22:54 UTC, ferantivero commented on pre-cluster-stamp.bicep
> +resource pdzKv 'Microsoft.Network/privateDnsZones@2020-06-01' existing = {
another bookmark comment to discuss about this. Not so sure why is this created even earlier.

2022-12-30 10:27 UTC, v-fearam commented on azuredeploy.parameters.prod.json
> +      "value": "[Your cluster will be bootstrapped from this branch in the identified git repo.]"
done

2022-12-30 10:28 UTC, v-fearam commented on cluster-manifests/flux-system/kustomization.yaml
> -  newName: REPLACE_ME_WITH_YOUR_ACRNAME.azurecr.io/live/fluxcd/source-controller
In the previous version flux as installed from the JumBox marching by hand, It was removed from there-

2022-12-30 10:30 UTC, v-fearam commented on cluster-manifests/flux-system/limit-range.yaml
> +  - max:
It was removed in the the first try, and was back with some properties commented out as Chad suggestions.

2022-12-30 10:32 UTC, v-fearam commented on docs/deploy/09-pre-cluster-stamp.md
> +   az deployment group create -g rg-bu0001a0005 -f pre-cluster-stamp.bicep -p targetVnetResourceId=${RESOURCEID_VNET_CLUSTERSPOKE} aksIngressControllerCertificate=${INGRESS_CONTROLLER_CERTIFICATE_BAS
let discuss in a meeting, I 'm not following your point. I will call you later on.

2022-12-30 10:35 UTC, v-fearam commented on pre-cluster-stamp.bicep
> +resource pdzKv 'Microsoft.Network/privateDnsZones@2020-06-01' existing = {
We need create early the key vaults, The Chad'sidea sis to do a complete creation, all thing related to key vault which ara able to be done at the point together here. We can discuss later on when I call you.

2022-12-30 14:23 UTC, ckittel approved these changes
LGTM, but please work with @ferantivero on any of the feedback he's got as well.  But you've addressed all my open items!  Nice!

2022-12-30 14:24 UTC, ckittel commented on cluster-manifests/flux-system/limit-range.yaml
> +  - max:
We left the files in to show an example of how you could even have influence over extensions in your regulated cluster.  We left the "safe" ones one (we can't really control the others.

2022-12-30 14:25 UTC, ckittel commented on cluster-manifests/flux-system/resource-quota.yaml
>      count/pods: "4"
We are leaving it in as an example of what control points you have in your cluster.  We just can't set the ones that are commented out.  Those lines could be removed if that is confusing.  The remaining ones are pretty safe though to keep in.

2022-12-30 14:27 UTC, ckittel commented on docs/deploy/09-pre-cluster-stamp.md
> +   az deployment group create -g rg-bu0001a0005 -f pre-cluster-stamp.bicep -p targetVnetResourceId=${RESOURCEID_VNET_CLUSTERSPOKE} aksIngressControllerCertificate=${INGRESS_CONTROLLER_CERTIFICATE_BAS
Ideally before, as @v-fearam has it, as we want immediate and complete bootstrapping where practical.

2022-12-30 14:28 UTC, ckittel commented on pre-cluster-stamp.bicep
> +resource pdzKv 'Microsoft.Network/privateDnsZones@2020-06-01' existing = {
Yeah, I'm not so sure we need the private DNS zones this early in the process.  I didn't think through if that would be better happening back where it was before.  Probably fine to move back into the cluster creation, yeah?

2022-12-30 17:20 UTC, ferantivero commented on cluster-manifests/flux-system/kustomization.yaml
> -  newName: REPLACE_ME_WITH_YOUR_ACRNAME.azurecr.io/live/fluxcd/source-controller
as discussed offline it is already covered.

2022-12-30 17:28 UTC, ferantivero commented on cluster-manifests/flux-system/limit-range.yaml
> +  - max:
Oh I see the point. 

Perhaps we could've added some note to tell our users that commented out fields should not be modified since it may cause unknown results or it won't be just taken into consideration.

In the meantime Im resolving this feedback for now as this was intended to be this way.

2022-12-30 17:31 UTC, ferantivero commented on pre-cluster-stamp.bicep
> +resource pdzKv 'Microsoft.Network/privateDnsZones@2020-06-01' existing = {
as discussed offline with @v-fearam this ok to be added along with the kv since it might be beneficial when sharing the resource while it is also a good idea to be added as it was before in case this resource is owned by the cluster exclusively.

At this moment I would like to resolve this feedback for the sake of getting this merged before today EoD.

2022-12-30 17:36 UTC, ferantivero commented on docs/deploy/09-pre-cluster-stamp.md
> +   az deployment group create -g rg-bu0001a0005 -f pre-cluster-stamp.bicep -p targetVnetResourceId=${RESOURCEID_VNET_CLUSTERSPOKE} aksIngressControllerCertificate=${INGRESS_CONTROLLER_CERTIFICATE_BAS
yeah, this is correct. While my proposal would've been less intrusive than the current one it is a good idea to have some day0 desire state (pre) for security reasons or similar.

please let me resolve this comment for now.

2022-12-30 17:36 UTC, ferantivero commented on cluster-stamp.bicep
> +resource kvsAppGwIngressInternalAksIngressTls 'Microsoft.KeyVault/vaults/secrets@2021-11-01-preview' existing = {
I would like to keep this one open while I will approve this PR for now.

2022-12-30 17:38 UTC, ferantivero approved these changes
great piece of work @v-fearam LGTM 🚢

2022-12-30 17:46 UTC, merged