feat (in-cluster infra): [upgrade oss] bump kured to 1.12.0 and azm cfg
mspnp/aks-baseline-regulated pull request #76
Opened 2023-01-18 20:59 UTC by ferantivero

closes partially: #23809 

## WHY

we want to keep every oss in-cluster up to date and align manifests with upstream in this case with baseline template.

## WHAT Changed?

- Updated kured to latest version (1.9.2 -> 1.12.0) and synced yaml manifests with upstream
- Updated Azure Monitor's configuration to be synced with upstream

## HOW to Test?

clone the repo and follow the instructions. After provisioning the AKS regulated cluster it should be running kured 1.12.0 and azm configuration should be similar to the aks baseline.

2023-02-15 14:21 UTC, ckittel requested changes

2023-02-15 14:21 UTC, ckittel commented on cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml
> +          exclude_namespaces = ["kube-system","gatekeeper-system"]
On the regulated cluster, we didn't exclude any namespaces to ensure maximum logging.  Looks like we're now excluding these?

2023-02-15 14:21 UTC, ckittel commented on cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml
> +          exclude_namespaces = ["kube-system","gatekeeper-system"]
On the regulated cluster, we didn't exclude any namespaces to ensure maximum logging.  Looks like we're now excluding these?

2023-02-15 14:21 UTC, ckittel commented on cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml
> +          enabled = false
Any reason to make this false now on regulated?

2023-02-15 14:21 UTC, ckittel commented on cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml
> +          containerlog_schema_version = "v2"
Awesome, thanks!

I assume this impacted some of our queries we ship?  Simplifies them so we don't need to do the nasty joins

2023-02-15 14:21 UTC, ckittel commented on cluster-manifests/cluster-baseline-settings/kured/kured.yaml
> +          image: ghcr.io/kubereboot/kured:1.12.0
I didn't see a change to the kustomization file yet:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/671075/219053297-fc7abdcb-daa9-4319-b0dd-a541782793dd.png">

2023-02-15 14:22 UTC, ckittel commented on cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml
> +          containerlog_schema_version = "v2"
To be clear, we don't have to simplify them in this PR, but if there are any obvious ones (like in the "try it" section or something), might be a good idea to do so, otherwise it's going to look weird to have joins that no longer need to be there.

2023-02-16 14:37 UTC, ferantivero commented on cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml
> +          exclude_namespaces = ["kube-system","gatekeeper-system"]
thanks for calling this out @ckittel,

done | addressed from c33cd602f15c7104408b6791948ab273b076a2f5

2023-02-16 14:37 UTC, ferantivero commented on cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml
> +          exclude_namespaces = ["kube-system","gatekeeper-system"]
thanks for calling this out @ckittel,

done | addressed from c33cd602f15c7104408b6791948ab273b076a2f5

2023-02-16 14:38 UTC, ferantivero commented on cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml
> +          enabled = false
you got it @ckittel,

done | addressed from 48ba822c162f50ca69d99a073fff509d42271f3f

2023-02-16 14:39 UTC, ferantivero commented on cluster-manifests/cluster-baseline-settings/kured/kured.yaml
> +          image: ghcr.io/kubereboot/kured:1.12.0
good catch @ckittel,

done | addressed from 6b4e71d0268649d62b1bb70c5e58cb6158ad7b40

2023-02-16 14:42 UTC, ferantivero commented on cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml
> +          containerlog_schema_version = "v2"
oh I see @ckittel, please let me take a look at those queries and see what we can do with them.

2023-03-01 18:40 UTC, ferantivero commented on cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml
> +          containerlog_schema_version = "v2"
@ckittel, we've updated from `ContainerLog` to `ContainerLogV2`.

done | addressed from 153386e602d75e7c4ccbd572f827f9fb368c0549

2023-03-01 20:24 UTC, ferantivero commented on cluster-manifests/kube-system/container-azm-ms-agentconfig.yaml
> +          containerlog_schema_version = "v2"
@ckittel, changed this a bit based on our offline syncup 

done | addressed from b0509747d68deeb1e63e37891c467b982ab279e5

2023-03-01 22:53 UTC, merged