feat (in-cluster infra): [upgrade oss] bump falco to 0.33.1
mspnp/aks-baseline-regulated pull request #78
Opened 2023-01-19 01:54 UTC by ferantivero

closes partially: #23809 

## WHY

we want to keep every oss in-cluster up to date and align manifests with upstream in this case with [falco template repo](https://github.com/falcosecurity/deploy-kubernetes/tree/0faf1e702b4f4508414d9b14d178670d782ce25d/kubernetes/falco/templates).

## WHAT Changed?

- Updated falco to latest version (0.29.1 -> 0.33.1) and synced yaml manifests with upstream

## HOW to Test?

clone the repo and follow the instructions. After provisioning the AKS regulated cluster it should be running flaco 0.33.1.

2023-02-27 14:56 UTC, ckittel requested changes
Just a couple small things.  Thanks!

2023-02-27 14:56 UTC, ckittel commented on cluster-manifests/falco-system/daemonset.yaml
> +          tty: false
Is there a value missing here?

2023-02-27 14:56 UTC, ckittel commented on cluster-manifests/falco-system/daemonset.yaml
> +              cpu: 1000m
How does this work in conjunction with https://github.com/mspnp/aks-baseline-regulated/blob/main/cluster-manifests/falco-system/limit-range.yaml?  Wouldn't this violate that?  Okay to make this limit larger, but I'd think you'd need to update the limit-range.yaml and maybe even the resource-quota.yaml file as well

2023-02-27 23:29 UTC, ferantivero commented on cluster-manifests/falco-system/daemonset.yaml
> +              cpu: 1000m
I though this change would be enough for this https://github.com/mspnp/aks-baseline-regulated/pull/78/files#diff-800c6254db931c761332625e7c61495c63309faabe16fa72cb123e205b2fcc17.

2023-02-27 23:31 UTC, ferantivero commented on cluster-manifests/falco-system/daemonset.yaml
> +          tty: false
I think it is ok to leave that blank as long as you want the driver loader not to be skipped.

2023-02-28 13:56 UTC, ckittel commented on cluster-manifests/falco-system/daemonset.yaml
> +              cpu: 1000m
You're right, I missed it (marked the file as "Viewed" but don't remember seeing it -- might have misclicked).  Anything need to change in resource quota?

2023-02-28 13:57 UTC, ckittel commented on cluster-manifests/falco-system/daemonset.yaml
> +          tty: false
so it wouldn't be better to just put `false` in there to be explicit?  Not sure I follow why leaving that blank is desirable.

2023-02-28 15:03 UTC, ferantivero commented on cluster-manifests/falco-system/daemonset.yaml
> +          tty: false
Oh sorry I didn't understand the ask in first place. It is just how it is from upstream. But yeah, Im totally fine setting to `false` value in there. Please let me check whether that works

2023-02-28 16:33 UTC, ferantivero commented on cluster-manifests/falco-system/daemonset.yaml
> +          tty: false
you got it @ckittel,

done | addressed from 1553d00689d1a0cff24ae9949dc6fb76fb71001a

2023-02-28 16:38 UTC, ferantivero commented on cluster-manifests/falco-system/daemonset.yaml
> +              cpu: 1000m
I think it is working just fine @ckittel, but I took the opportunity to revisit the object and find a small opportunity for improvement: d5b7e1051eb6ac3f0a56cf628f8173f9fa04b4cc

2023-02-28 18:18 UTC, ckittel approved these changes
LGTM, thanks!

2023-03-01 23:05 UTC, merged